name: ðŸ› Bug Report
description: Report a problem to help us improve.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
  - type: input
    id: district
    attributes:
      label: Fire District
      description: Which Victorian fire district are you located in? (e.g., Central, North Central)
      placeholder: e.g. Central
    validations:
      required: true
  - type: input
    id: ha_version
    attributes:
      label: Home Assistant Version
      description: e.g. 2024.1.2
      placeholder: e.g. 2024.1.2
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please provide logs from 'Settings -> System -> Logs' if applicable.
      render: shell
