name: "💡 Feature Request"
description: "Suggest an idea or improvement for this integration."
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! We're always looking to make the Victoria Fire Danger integration better for everyone.
  - type: textarea
    id: feature-description
    attributes:
      label: "What feature would you like to see?"
      description: "A clear and concise description of what you want to happen."
      placeholder: "e.g., I'd like to see the 'Total Fire Ban' status as a separate sensor..."
    validations:
      required: true
  - type: textarea
    id: problem-solved
    attributes:
      label: "Is your feature request related to a problem?"
      description: "Please describe the problem you are trying to solve."
      placeholder: "e.g., Currently, it's hard to tell if today is a Total Fire Ban day at a glance."
  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: "Any other ways you've thought about solving this?"
  - type: markdown
    attributes:
      value: |
        ---
        *Note: If this is your first time contributing an idea, thank you! Your input helps keep Victorians safe.*
